#!/bin/sh

PNAME=Cocoa
SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -r ../${PNAME} /tmp

rm -f /tmp/${PNAME}/mkdist

cd /tmp/${PNAME}

echo "Removing CVS and backup stuff ..."
find . -name CVS -or -name .svn | xargs rm -rf
find . -name \*~ | xargs rm -f

VER=`awk -v ORS= '/Version:/ { print $2 }' DESCRIPTION`

#echo "Updating version ..."
#VER=`awk -v ORS= '/JavaGD v/ { print substr($6,2) }' src/javaGD.h`
#echo "JavaGD version ${VER}"
#cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
#mv d DESCRIPTION
echo "Creating package ..."
cd ..
tar fcz ${PNAME}_${VER}.tar.gz ${PNAME}
cd ${SWD}
cp /tmp/${PNAME}_${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz
